import React from 'react'
import Head from 'next/head'
import Navigation from '../../components/Navigation'
import Header from '../../components/Header'
import Footer from '../../components/Footer'
import About from '../../components/About/About'

function index() {
  return (
    
    <div className="flex flex-col min-h-screen bg-white">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow container mx-auto ">
        <Header/>
           <About/>
          <div className="absolute z-10 right-0 xl:right-0 xl:top-28 lg:top-28 -bottom-38 xl:bottom-0 lg:w-fit w-full bg-white">
          <aside className="transform xl:translate-y-40  p-4">
            <Navigation/>
          </aside>
          </div>
      </main>
    </div>
    
  )
}

export default index